# Generated by Django 3.1.3 on 2020-12-08 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='display_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='email',
        ),
        migrations.RemoveField(
            model_name='category',
            name='password',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_type',
        ),
    ]
