# Generated by Django 3.1.4 on 2020-12-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20201212_2005'),
        ('rareapi', '0002_auto_20201212_1800'),
    ]

    operations = [
    ]
