# Generated by Django 3.1.4 on 2021-01-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20210106_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
    ]
