# Generated by Django 3.1.4 on 2020-12-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20201219_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rareuser',
            options={},
        ),
    ]
