# Generated by Django 3.1.4 on 2021-01-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20210105_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='rareuser',
            name='profile_image_url',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
        migrations.DeleteModel(
            name='UserAvatar',
        ),
    ]
