# Generated by Django 3.1.4 on 2021-01-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_auto_20210109_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='rareuser',
            name='subscriptions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_ids', related_query_name='subscription_author_id', to='rareapi.subscription'),
        ),
    ]
