# Generated by Django 3.1.4 on 2021-01-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_auto_20210109_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_img_url',
            field=models.ImageField(null=True, upload_to='headerimg'),
        ),
    ]
