# Generated by Django 3.1.4 on 2020-12-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_auto_20201209_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
