# Generated by Django 3.1.4 on 2021-01-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_rareuser_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='ended_on',
        ),
    ]
