# Generated by Django 3.1.4 on 2020-12-15 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_auto_20201215_0027'),
        ('rareapi', '0003_merge_20201215_0022'),
    ]

    operations = [
    ]
